{% set version = "2.0.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ic10trainingdata
  version: {{ version|replace("-", "_") }}

source:
  fn: iC10TrainingData_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/iC10TrainingData_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/iC10TrainingData/iC10TrainingData_{{ version }}.tar.gz
  sha256: 5e8ce761046424e1fb2c85e336d120469e7bd3e8068ea07bbfbdd3dcb32b4b41

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('iC10TrainingData')"           # [not win]
    - "\"%R%\" -e \"library('iC10TrainingData')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=iC10TrainingData
  license: GPL-3
  summary: Training datasets for iC10; which implements the classifier described in the paper 'Genome-driven integrated classification of breast cancer validated in over 7,500 samples' (Ali HR et al., Genome Biology 2014). It uses copy number and/or expression form breast cancer data, trains a pamr classifier (Tibshirani
    et al.) with the features available and predicts the iC10 group. Genomic annotation for the training dataset has been obtained from Mark Dunning's lluminaHumanv3.db package.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
