travis:
  secure:
    BINSTAR_TOKEN: AiOVryFVSwQFuMnnTtV4UYoBZ81uV/4BKl3JWlaJuxfYJmIR5CHOJ+/6YCLNGgJg3Bi30t/kBF3rcOxMXKMvPsHwGS2+5ygmrG24n/VkGD3W0jthwCjWoNYZv18sgJyNXwYXZ3SRCQiY9I2TUjxgznZ9AMZqsm4+KFqhdlOyPYvMjX7DwY0sM3iV1hzHJ1xI+kT6t/sJcrr7W634lo4fdjZZZyKFRShmP3Ifwmew5ZF7Mhn6AcMl0XSQ19SDVJ6J6dyc91iLpDrXq6bjslL2MXh/j8iqInv+21ha1r432qxyAnTaKMt0MNLZxJ0b2QygmGlZYSf9//PtrdmGYIKQmtNlcWEQFTSsjES/mayJNRTzG8eR9g5nq6bHJXzndqOeJwo194+dMq0AWIySwIzx6ctmPD3LX2EqsU+k41cocr0BsZ/gPPpiAbLXJx4SjaIpBgG9GQ2meu/LQtY5sVFWY4UoMEJOUmqqRymVCs8eUqtzqo9kTOhlOowgJCpCBO4Ni6aGDbdLS2twz4i6HLybRAYPq9ajgfCbwGyBdwmRPfZ0fhlSNnAilGTa1KZGju8/vtBDdF/SxRucQd24CbY3Yt1DLA5kOJJ0quzrk1FhpdDnvCJpitZgmctE7d06IypiH3JarTIWcRSck8zIJ9fKmQ+fMZ5kxy/v9RVhyNFQdyg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
